apiVersion: v1
kind: Service
metadata:
  name: webrtc-app-service
  namespace: stunner-system
spec:
  type: LoadBalancer
  selector:
    app: webrtc-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
